import type { Metadata } from "next";
import { profile, siteUrl } from "@/content/profile";
import {
  defaultLocale,
  htmlLang,
  locales,
  ogLocale,
  previewLocale,
  type Locale,
} from "@/i18n/config";
import { getDictionary, type Dictionary } from "@/i18n/get-dictionary";

/** Open Graph image generated by `app/[lang]/opengraph-image.tsx`. */
export const ogImage = {
  id: "og",
  size: { width: 1200, height: 630 },
  contentType: "image/png",
} as const;

function languageAlternates(): Record<string, string> {
  const entries = locales.map((l) => [htmlLang[l], `/${l}`] as const);
  return {
    ...Object.fromEntries(entries),
    "x-default": `/${defaultLocale}`,
  };
}

export function buildMetadata(locale: Locale, dict: Dictionary): Metadata {
  return {
    metadataBase: new URL(siteUrl),
    title: dict.meta.title,
    applicationName: profile.shortName,
    authors: [{ name: profile.name, url: siteUrl }],
    creator: profile.name,
    alternates: {
      canonical: `/${locale}`,
      languages: languageAlternates(),
    },
    ...sharePreview(locale, dict),
    robots: { index: true, follow: true },
  };
}

/**
 * Metadata for the `/` redirect page. Link-preview crawlers don't run the
 * redirect script, so it carries the preview of `previewLocale`, with the
 * image pointed at explicitly because it lives under `/[lang]`.
 */
export function buildRedirectMetadata(): Metadata {
  const dict = getDictionary(previewLocale);
  const preview = sharePreview(previewLocale, dict);

  return {
    metadataBase: new URL(siteUrl),
    title: profile.shortName,
    alternates: { languages: languageAlternates() },
    ...preview,
    openGraph: {
      ...preview.openGraph,
      images: {
        url: `/${previewLocale}/opengraph-image/${ogImage.id}`,
        alt: dict.meta.ogAlt,
        type: ogImage.contentType,
        ...ogImage.size,
      },
    },
    robots: { index: false, follow: true },
  };
}

/** Description, Open Graph and Twitter card fields shared by both pages. */
function sharePreview(locale: Locale, dict: Dictionary) {
  const { title, description } = dict.meta;

  return {
    description,
    openGraph: {
      type: "profile",
      url: `/${locale}`,
      siteName: profile.shortName,
      title,
      description,
      locale: ogLocale[locale],
      alternateLocale: locales
        .filter((l) => l !== locale)
        .map((l) => ogLocale[l]),
      firstName: profile.firstName,
      lastName: profile.lastName,
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  } satisfies Metadata;
}

export function personJsonLd(locale: Locale, dict: Dictionary) {
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    name: profile.name,
    alternateName: profile.shortName,
    url: `${siteUrl}/${locale}`,
    email: `mailto:${profile.email}`,
    jobTitle: dict.hero.role,
    address: {
      "@type": "PostalAddress",
      addressLocality: "Contagem",
      addressRegion: "MG",
      addressCountry: "BR",
    },
    sameAs: profile.social.map((link) => link.href),
    knowsLanguage: ["pt-BR", "en"],
  };
}
